from datetime import timedelta

# Error codes
VALIDATION_FAILED = "VALIDATION_FAILED"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY"
INVALID_OPERATION = "INVALID_OPERATION"
WAREHOUSE_CODE_IMMUTABLE = "WAREHOUSE_CODE_IMMUTABLE"
WAREHOUSE_HAS_ACTIVE_INVENTORY = "WAREHOUSE_HAS_ACTIVE_INVENTORY"
PO_HAS_NO_ITEMS = "PO_HAS_NO_ITEMS"
SELF_APPROVAL_NOT_ALLOWED = "SELF_APPROVAL_NOT_ALLOWED"
PO_CANCELLATION_NOT_ALLOWED = "PO_CANCELLATION_NOT_ALLOWED"
INSUFFICIENT_STOCK_FOR_ORDER = "INSUFFICIENT_STOCK_FOR_ORDER"

# Cache keys and TTLs
INVENTORY_LOW_STOCK_KEY = "inventory:low-stock"
INVENTORY_LOW_STOCK_TTL = 300
PO_SEQUENCE_KEY_TEMPLATE = "po-sequence:{}"
PO_SEQUENCE_TTL = 86400
