# Generated by Django 5.2.14 on 2026-06-06 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0002_salesorder_created_by_salesorder_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='quantity_ordered',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quantity_shipped',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
